name: Publish to Cloudsmith
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Configure credentials for private Cargo registry `rocsys-rust`
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.CLOUDSMITH_GIT_CREDENTIALS }}
      - name: Check Package Version
        id: version
        run: |
          TAG_VERSION=$(echo "${{ github.ref }}" | sed -rn 's/^refs\/tags\/v(.*)$/\1/p')
          if [ -z "${TAG_VERSION}" ]; then
            echo "Failed to extract tag version from ref \`${{ github.ref }}\`!"
            exit 1
          fi

          PACKAGE_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | select(.name == "temp-mongo") | .version')
          if [ -z "${PACKAGE_VERSION}" ]; then
            echo "Failed to extract package version from Cargo.toml!"
            exit 1
          fi

          if [[ "${TAG_VERSION}" != ${PACKAGE_VERSION} ]]; then
            echo "::error file=Cargo.toml,title=Version Mismatch::Expected the git tag version \`${TAG_VERSION}\` and the package version \`${PACKAGE_VERSION}\` to be the same but they are not!"
            exit 1
          fi

          echo "::set-output name=version::${PACKAGE_VERSION}"
      - name: Push to Cloudsmith Cargo registry
        run: |
          pip install --upgrade cloudsmith-cli
          cargo package --package rocsys-settings-service-client
          cloudsmith push cargo rocsys/rust "target/package/temp-mongo-${{steps.version.outputs.version}}.crate" --api-key="${{ secrets.CLOUDSMITH_CI_API_KEY }}"
