name: CI Docker
on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches: ["*"]

jobs:
  stable:
    name: Build and test on stable
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Docker Daemon
        run: |
          sudo service docker start

      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build (tokio)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color=always --all-targets

      - name: Test (tokio)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always

      - name: Build (async-std)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color=always --no-default-features --features async-std-runtime --all-targets

      - name: Test (async-std)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always --no-default-features --features async-std-runtime
