name: Rust CI (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run MongoDB in Docker
        run: |
          docker run --name mongodb -d -p 27017:27017 mongo:4.4.6
          # Wait for MongoDB to fully start
          Start-Sleep -Seconds 10

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always --no-default-features --features async-std-runtime
